sonar.projectKey=Isaacgc1999_safeBAItes_app
sonar.organization=isaacgc1999
sonar.projectName=safebits
sonar.sources=safebits_front/src,safebits_back/src,packages/shared/src,tools/lint/src
sonar.tests=safebits_front/src,safebits_back/src,packages/shared/src,tools/lint/src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=safebits_front/coverage/safebits-front/lcov.info,safebits_back/coverage/lcov.info,packages/shared/coverage/lcov.info,tools/lint/coverage/lcov.info
sonar.sourceEncoding=UTF-8
