name: Database Migrations

on:
  workflow_dispatch:

jobs:
  migrate-staging:
    environment: safebits-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
      - run: supabase db push --db-url "postgresql://postgres.fubfjoytzfjybiygfjgu:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-1-eu-central-1.pooler.supabase.com:5432/postgres"

  migrate-production:
    environment: safebits-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
      - run: supabase db push --db-url "postgresql://postgres.wpghxzsydnooyrvleohd:${{ secrets.SUPABASE_DB_PASSWORD }}@aws-0-eu-west-1.pooler.supabase.com:5432/postgres"
